import type { OrbitTool } from '../types'
import { getContext, notify } from './local'
import { deepResearch, spawnAgents, startBackgroundTask } from './agents'
import { listIntegrations } from './integrations'
import { forget, recall, remember } from './memory'
import { cancelReminder, listReminders, setReminder } from './reminders'
import { createWorkflow, deleteWorkflow, listWorkflows, runWorkflow, workflowGuide } from './workflows'
import { webFetch, webSearch } from './web'
import { readFeed } from './feeds'
import { makeFile, readSavedFile, saveFile } from './files'
import { listFolder, readFile } from './folders'
import { askUserTool } from './ask'
import { suggestMemory } from './suggest'
import { listChanges, undoChangeTool } from './undo'
import { copyFile, createFile, deleteFiles, editFile, moveFiles } from './writeFiles'
import { runCommand, runPythonTool } from './code'
import { browserAct, browserLook } from './browser'
import { useSkill } from './skills'

export const builtinTools = [webSearch, webFetch, notify, getContext, remember, recall, forget, listIntegrations, startBackgroundTask, spawnAgents, setReminder, listReminders, cancelReminder, workflowGuide, createWorkflow, listWorkflows, runWorkflow, deleteWorkflow, readFeed, saveFile, readSavedFile, makeFile, listFolder, readFile, askUserTool, suggestMemory, listChanges, undoChangeTool, createFile, editFile, moveFiles, deleteFiles, copyFile, runPythonTool, runCommand, browserLook, browserAct, useSkill, deepResearch] as unknown as OrbitTool[]
